
####
# This is REST Client tool i use this to test endpoints
####
### This is 'GET' request for 'listSchools'

GET https://school-manage-production.up.railway.app/listSchools?latitude=28.5636&longitude=77.1721


### This is 'POST' request for 'addSchool'

### 1
POST https://school-manage-production.up.railway.app/addSchool
Content-Type: application/json

{
    "name": "Delhi Public School",
    "address": "Sector 24, R.K. Puram, New Delhi, 110022",
    "latitude": 28.5636,
    "longitude": 77.1721
}

### 2
POST https://school-manage-production.up.railway.app/addSchool
Content-Type: application/json

{
    "name": "Delhi Public School",
    "address": "Sector 24, R.K. Puram, New Delhi, 110022",
    "latitude": 28.5636,
    "longitude": 77.1721
}

###3
POST https://school-manage-production.up.railway.app/addSchool
Content-Type: application/json

{
    "name": "Santhome Public School",
    "address": "Sector 24, R.K. Puram, New Delhi, 110022",
    "latitude": 28.5636,
    "longitude": 77.1721
}

### 4
POST https://school-manage-production.up.railway.app/addSchool
Content-Type: application/json

{
    "name": "St. John's Public School",
    "address": "Sector 24, R.K. Puram, New Delhi, 110022",
    "latitude": 28.5636,
    "longitude": 77.1721
}
